/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppNovoEstudoRouteImport } from './routes/app.novo-estudo'
import { Route as AppCarregandoRouteImport } from './routes/app.carregando'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNovoEstudoRoute = AppNovoEstudoRouteImport.update({
  id: '/novo-estudo',
  path: '/novo-estudo',
  getParentRoute: () => AppRoute,
} as any)
const AppCarregandoRoute = AppCarregandoRouteImport.update({
  id: '/carregando',
  path: '/carregando',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/carregando': typeof AppCarregandoRoute
  '/app/novo-estudo': typeof AppNovoEstudoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/carregando': typeof AppCarregandoRoute
  '/app/novo-estudo': typeof AppNovoEstudoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/carregando': typeof AppCarregandoRoute
  '/app/novo-estudo': typeof AppNovoEstudoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/carregando' | '/app/novo-estudo' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/carregando' | '/app/novo-estudo' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/carregando'
    | '/app/novo-estudo'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/novo-estudo': {
      id: '/app/novo-estudo'
      path: '/novo-estudo'
      fullPath: '/app/novo-estudo'
      preLoaderRoute: typeof AppNovoEstudoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carregando': {
      id: '/app/carregando'
      path: '/carregando'
      fullPath: '/app/carregando'
      preLoaderRoute: typeof AppCarregandoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCarregandoRoute: typeof AppCarregandoRoute
  AppNovoEstudoRoute: typeof AppNovoEstudoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarregandoRoute: AppCarregandoRoute,
  AppNovoEstudoRoute: AppNovoEstudoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
